# Generated by Django 5.1.1 on 2024-10-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('component', models.CharField(max_length=255)),
                ('alert_value', models.IntegerField(max_length=255)),
            ],
        ),
    ]
