# Generated by Django 5.1.1 on 2024-10-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedalert',
            name='alert_value',
            field=models.IntegerField(),
        ),
    ]
