# Generated by Django 5.1.1 on 2024-11-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alter_savedalert_alert_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=256)),
                ('chat_id', models.CharField(max_length=50)),
            ],
        ),
    ]
