# Generated by Django 5.1.1 on 2024-11-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_telegramcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedalert',
            name='chadID',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
