# Generated by Django 5.1.1 on 2024-11-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_savedalert_chadid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedalert',
            old_name='chadID',
            new_name='chatID',
        ),
    ]
