# Generated by Django 5.1.1 on 2024-11-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_rename_chadid_savedalert_chatid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramcredentials',
            name='api_key',
        ),
        migrations.AddField(
            model_name='telegramcredentials',
            name='encrypted_api_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
