# Generated by Django 5.1.1 on 2024-11-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_remove_telegramcredentials_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramcredentials',
            name='alertMessage',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
