# Generated by Django 5.1.1 on 2024-11-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_telegramcredentials_alertmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramcredentials',
            name='alertMessage',
        ),
        migrations.AddField(
            model_name='savedalert',
            name='alertMessage',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
